version: '3'

services: 
  lenses:
    image: lensesio/box
    container_name: lenses_dev
    env_file: 
      - lenses.env
    environment: 
      - ADV_HOST=127.0.0.1
    ports:
      - 3030:3030
      - 9092:9092
    volumes: 
      - lenses_data:/data
  
volumes:
  lenses_data:
